# Generated by Django 5.2.8 on 2026-03-04 10:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('ciclo_cobranca', models.CharField(choices=[('MENSAL', 'Mensal'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('limite_usuarios', models.PositiveIntegerField(default=1)),
                ('limite_registros', models.PositiveIntegerField(default=100)),
                ('recursos_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome_completo', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('cargo', models.CharField(choices=[('SUPORTE', 'Suporte'), ('COMERCIAL', 'Comercial'), ('FINANCEIRO', 'Financeiro'), ('ADMINISTRADOR', 'Administrador')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('perfil', models.CharField(choices=[('SUPERADMIN', 'Superadmin'), ('SUPORTE', 'Suporte'), ('FINANCEIRO', 'Financeiro'), ('COMERCIAL', 'Comercial')], default='SUPORTE', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('ultimo_login', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('documento', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('status_assinatura', models.CharField(choices=[('ATIVA', 'Ativa'), ('SUSPENSA', 'Suspensa'), ('CANCELADA', 'Cancelada'), ('TESTE', 'Teste')], default='TESTE', max_length=20)),
                ('inicio_assinatura', models.DateField(blank=True, null=True)),
                ('fim_teste', models.DateField(blank=True, null=True)),
                ('nome_banco', models.CharField(blank=True, max_length=200)),
                ('usuario_banco', models.CharField(blank=True, max_length=120)),
                ('senha_banco', models.CharField(blank=True, max_length=200)),
                ('host_banco', models.CharField(blank=True, max_length=120)),
                ('porta_banco', models.CharField(blank=True, max_length=20)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='core.plano')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIAR', 'Criar'), ('EDITAR', 'Editar'), ('EXCLUIR', 'Excluir'), ('ATIVAR', 'Ativar'), ('INATIVAR', 'Inativar'), ('LOGIN', 'Login')], max_length=20)),
                ('entidade', models.CharField(max_length=120)),
                ('objeto_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=60)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('dados_json', models.JSONField(blank=True, default=dict)),
                ('usuario_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.usuarioadmin')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
