# Generated by Django 5.2.8 on 2026-03-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='motor_banco',
            field=models.CharField(blank=True, default='sqlite', max_length=20),
        ),
    ]
