# Generated by Django 5.2.8 on 2026-03-04 13:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fornecedor_servico_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150)),
                ('instituicao', models.CharField(blank=True, max_length=150)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VendaCentral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=150)),
                ('cliente', models.CharField(max_length=150)),
                ('data_venda', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FATURADA', 'Faturada'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=20)),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=150)),
                ('data_vencimento', models.DateField(default=django.utils.timezone.localdate)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('PAGA', 'Paga'), ('ATRASADA', 'Atrasada')], default='ABERTA', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
                ('conta_financeira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='core.contafinanceira')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar', to='core.fornecedor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=150)),
                ('data_recebimento', models.DateField(default=django.utils.timezone.localdate)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('PREVISTA', 'Prevista'), ('RECEBIDA', 'Recebida'), ('ATRASADA', 'Atrasada')], default='PREVISTA', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
                ('conta_financeira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receitas', to='core.contafinanceira')),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receitas', to='core.vendacentral')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
