from django.urls import path

from crm import views

urlpatterns = [
    path("acesso-empresa", views.login, name="crm_login"),
    path("sair-empresa", views.logout, name="crm_logout"),
    path("app", views.dashboard, name="crm_dashboard"),
    path("app/profissionais", views.listagem, {"entidade": "profissionais"}, name="crm_profissionais_lista"),
    path("app/profissionais/novo", views.criar, {"entidade": "profissionais"}, name="crm_profissionais_novo"),
    path("app/profissionais/<int:pk>", views.detalhe, {"entidade": "profissionais"}, name="crm_profissionais_detalhe"),
    path("app/profissionais/<int:pk>/editar", views.editar, {"entidade": "profissionais"}, name="crm_profissionais_editar"),
    path("app/profissionais/<int:pk>/modal-excluir", views.modal_exclusao, {"entidade": "profissionais"}, name="crm_profissionais_modal_excluir"),
    path("app/profissionais/<int:pk>/excluir", views.excluir, {"entidade": "profissionais"}, name="crm_profissionais_excluir"),
    path("app/clientes", views.listagem, {"entidade": "clientes"}, name="crm_clientes_lista"),
    path("app/clientes/novo", views.criar, {"entidade": "clientes"}, name="crm_clientes_novo"),
    path("app/clientes/<int:pk>", views.detalhe, {"entidade": "clientes"}, name="crm_clientes_detalhe"),
    path("app/clientes/<int:pk>/editar", views.editar, {"entidade": "clientes"}, name="crm_clientes_editar"),
    path("app/clientes/<int:pk>/modal-excluir", views.modal_exclusao, {"entidade": "clientes"}, name="crm_clientes_modal_excluir"),
    path("app/clientes/<int:pk>/excluir", views.excluir, {"entidade": "clientes"}, name="crm_clientes_excluir"),
    path("app/produtos", views.listagem, {"entidade": "produtos"}, name="crm_produtos_lista"),
    path("app/produtos/novo", views.criar, {"entidade": "produtos"}, name="crm_produtos_novo"),
    path("app/produtos/<int:pk>", views.detalhe, {"entidade": "produtos"}, name="crm_produtos_detalhe"),
    path("app/produtos/<int:pk>/editar", views.editar, {"entidade": "produtos"}, name="crm_produtos_editar"),
    path("app/produtos/<int:pk>/modal-excluir", views.modal_exclusao, {"entidade": "produtos"}, name="crm_produtos_modal_excluir"),
    path("app/produtos/<int:pk>/excluir", views.excluir, {"entidade": "produtos"}, name="crm_produtos_excluir"),
    path("app/servicos", views.listagem, {"entidade": "servicos"}, name="crm_servicos_lista"),
    path("app/servicos/novo", views.criar, {"entidade": "servicos"}, name="crm_servicos_novo"),
    path("app/servicos/<int:pk>", views.detalhe, {"entidade": "servicos"}, name="crm_servicos_detalhe"),
    path("app/servicos/<int:pk>/editar", views.editar, {"entidade": "servicos"}, name="crm_servicos_editar"),
    path("app/servicos/<int:pk>/modal-excluir", views.modal_exclusao, {"entidade": "servicos"}, name="crm_servicos_modal_excluir"),
    path("app/servicos/<int:pk>/excluir", views.excluir, {"entidade": "servicos"}, name="crm_servicos_excluir"),
    path("app/vendas", views.listagem, {"entidade": "vendas"}, name="crm_vendas_lista"),
    path("app/vendas/nova", views.criar, {"entidade": "vendas"}, name="crm_vendas_novo"),
    path("app/vendas/<int:pk>", views.detalhe, {"entidade": "vendas"}, name="crm_vendas_detalhe"),
    path("app/vendas/<int:pk>/editar", views.editar, {"entidade": "vendas"}, name="crm_vendas_editar"),
    path("app/vendas/<int:pk>/modal-excluir", views.modal_exclusao, {"entidade": "vendas"}, name="crm_vendas_modal_excluir"),
    path("app/vendas/<int:pk>/excluir", views.excluir, {"entidade": "vendas"}, name="crm_vendas_excluir"),
    path("app/vendas/<int:pk>/itens", views.adicionar_item_venda, name="crm_vendas_itens"),
    path("app/vendas/<int:pk>/itens/<int:item_id>/remover", views.remover_item_venda, name="crm_vendas_item_remover"),
]
