# Generated by Django 5.2.8 on 2026-03-04 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoriaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIAR', 'Criar'), ('EDITAR', 'Editar'), ('EXCLUIR', 'Excluir'), ('INATIVAR', 'Inativar'), ('LOGIN', 'Login'), ('CANCELAR', 'Cancelar')], max_length=20)),
                ('entidade', models.CharField(max_length=120)),
                ('objeto_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=60)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('dados_json', models.JSONField(blank=True, default=dict)),
                ('usuario_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.usuarioempresa')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
